name: .NET TuneForge

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Optional: Commit SHA to checkout (defaults to current HEAD)'
        required: false
      release_message:
        description: 'Message to include in the release'
        required: true

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.411

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release -p:PreferredToolArchitecture=x64

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Create ZIP package with .exe and assets/
      run: |
        mkdir package
        xcopy /E /I /Y bin\Release\assets package\assets
        xcopy /Y bin\Release\*.dll package\assets\
        xcopy /Y bin\Release\*.pdb package\assets\
        xcopy /Y bin\Release\*.xml package\assets\
        xcopy /Y bin\Release\WpfTuneForgePlayer.exe package\
        powershell -Command "Compress-Archive -Path package\* -DestinationPath bin\Release\TuneForge.zip"

    - name: List ZIP content
      run: powershell -Command "Expand-Archive -Path bin\Release\TuneForge.zip -DestinationPath test_extract; dir test_extract -Recurse"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: "TuneForge Release"
        body: |
          • Commit: ${{ inputs.commit_sha || github.sha }}
          • Message: ${{ inputs.release_message }}
        files: bin/Release/TuneForge.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
